<?php

return [
    "1984. Der blonde Affe" => [
        "Hans Peter Hallwachs",
        "Wolfgang Büttner",
        "Charles Wirths",
        "Matthias Ponnier",
        "Andreas Mannkopff",
        "Andreas Szerda",
        "Bettina Roccor",
        "Monica Bleibtreu",
        "Hans Timerding",
        "Christian Brückner",
        "Berth Wesselmann",
        "Fritz Bachschmidt",
        "Friedrich von Bülow",
        "Hanna Burgwitz",
        "Helene Elcka",
        "Carola Erdin",
        "Fausto Guarnieri",
        "Paul-Albert Krumm",
        "Wolfgang Schwarz"
    ],
    "1984. Der Krieg mit den Molchen" => [
        "Jürgen Arndt",
        "Gustl Weishappel",
        "Dieter Brammer",
        "Christian Marschall",
        "Eduard Linkers",
        "Viktoria Naelin",
        "Michael Habeck",
        "Jochen Striebeck",
        "Helmut Stange",
        "Thomas Reiner",
        "Christoph Lindert"
    ],
    "1984. Der Park" => [
        "Jutta Lampe",
        "Bruno Ganz",
        "Martina Krauel",
        "Roland Schäfer",
        "Peter Simonischek",
        "Libgart Schwarz",
        "Walter Schmidinger",
        "Udo Samel"
    ],
    "1984. Die Brook-Street-Affäre" => [
        "Rolf Henniger",
        "Heinz Meier",
        "Matthias Ponnier",
        "Gerd Duwner",
        "Berth Wesselmann",
        "Hans Goguel",
        "Ruth Geiger",
        "Helmut Wöstmann"
    ],
    "1984. Ihr Name steht im Protokoll" => [
        "Ernst Schröder",
        "Rudolf Jürgen Bartsch",
        "Raoul Wolfgang Schnell",
        "Friedhelm Ptok",
        "Christian Brückner",
        "Christian Rode",
        "Klaus Nägelen",
        "Joachim Pukaß",
        "Helmut Wildt",
        "Gerd Holtenau",
        "Peter Matic",
        "Friedrich W. Bauschulte",
        "Andreas Thieck",
        "Rina Otterbach"
    ],
    "1984. Schlachthaus" => [
        "Bodo Primus",
        "Joachim Wichmann",
        "Edwin Noel",
        "Peter Fricke",
        "Günther Sauer",
        "Freddy Klaus",
        "Karin Anselm",
        "Andrea Dahmen",
        "Wilfried Klaus",
        "Andrea Rosenberg",
        "Alexander Malachovsky",
        "Heiner Schmidt",
        "Selestino Sanchez",
        "Renate Grosser"
    ],
    "1984. Spuren im Sand" => [
        "Klaus Kindler",
        "Robert Atzorn",
        "Diana Körner",
        "Gerd Andresen",
        "Armas Sten Fühler",
        "Hannes Groth"
    ],
    "1985. Interview" => [
        "Gert Günther Hoffmann"
    ],
    "1986. Auckland" => [
        "Rolf Becker",
        "Christian Brückner",
        "Wolfgang Höper",
        "Mascha Kataryna Huster",
        "Ernst Jacobi",
        "Hermann Lause",
        "Witta Pohl",
        "Hildegard Schmahl"
    ],
    "1986. Bullivants Match" => [
        "Matthias Ponnier",
        "Marianne Mosa",
        "Wolfgang Preiss",
        "Nina Danzeisen",
        "Christian Brückner",
        "Iris Eick",
        "Monika Hessenberg",
        "Horst Hildebrand",
        "Rainer Laupichler",
        "Alfred Querbach",
        "Christine Schulz",
        "Klaus Spürkel",
        "Hans Edgar Stecher",
        "Alois Garg",
        "Hans Wyprächtiger",
        "Berth Wesselmann",
        "Dorothée Reize",
        "Bodo Primus",
        "Andreas Szerda",
        "Gerd Andresen",
        "Michael Thomas",
        "Robert Rathke",
        "Charles Wirths",
        "Willi Schneider"
    ],
    "1986. Das Zittern des Fälschers" => [
        "Gerd David",
        "Fred C. Siebeck",
        "Christian Brückner",
        "Maren Kroymann",
        "Djelloul Ben Khelifa",
        "Elisabeth Wyrambe"
    ],
    "1986. Der Irrtum" => [
        "Wolfgang Condrus",
        "Sonja Deutsch",
        "Viola Sauer",
        "Gert Haucke",
        "Hans-Georg Panczak",
        "Elke Maria Wollmann",
        "Matthias Wendel",
        "Peter Seuser",
        "Joachim Seuser"
    ],
    "1986. Der Name der Rose" => [
        "Heinz Moog",
        "Christian Schulz",
        "Pinkas Braun",
        "Helmut Stange",
        "Manfred Steffen",
        "Wolfgang Reichmann",
        "Lukas Ammann",
        "Ernst Jacobi",
        "Rolf Boysen",
        "Paul Hoffmann",
        "Stefan Wigger",
        "Peter Lieck",
        "Markus Boysen",
        "Wolfgang Hinze",
        "Wolfgang Büttner",
        "Electra de Salvo",
        "Richard Münch",
        "Michael Habeck",
        "Martin Umbach"
    ],
    "1986. Der verlorene Horizont" => [
        "Klaus Abramowsky",
        "Wolf Euba",
        "Christian Marschall",
        "Manfred Seipold",
        "Peter Lieck",
        "Christoph Lindert",
        "Harry Kalenberg",
        "Renate Grosser",
        "Joost Siedhoff",
        "Peter Lühr",
        "Alois Maria Giani"
    ],
    "1986. Im Märzen Calpurnia die Nerven anspannt" => [
        "Kurt Raab",
        "Michael Habeck",
        "Enzi Fuchs",
        "Peter Thom",
        "Christa Bendl",
        "Konrad van Beust",
        "Christine Blumhoff",
        "Stefan Born",
        "Mario Pascalino",
        "Helmut Stange"
    ],
    "1987. Am Ende des Weges" => [
        "Hans-Helmut Dickow",
        "Till Hagen",
        "Gerrit Schmidt-Foss",
        "Evelyn Meyka",
        "Helmut Ahner",
        "Wolfgang Spier",
        "Otto Czarski",
        "Jonathan Kinsler",
        "Holly Jane Rahlens",
        "Monica Bielenstein",
        "René Geney",
        "Vera Kluth",
        "Manfred Schuster",
        "Rudolf Pinz",
        "Joachim Kirsten",
        "Thomas Petruo"
    ],
    "1987. Einer von Tausenden oder Der Denkzettel" => [
        "Chajim Koenigshofen",
        "Irina Wanka",
        "Gunnar Möller",
        "Heinz Schimmelpfennig",
        "Anke Hartwig",
        "Marianne Mosa",
        "Charles Wirths",
        "Timothy Peach",
        "Joachim Jung",
        "Michael Mendl",
        "Tobias Lelle",
        "Karl-Heinz Butzen",
        "Regina Faerber",
        "Eva Michel",
        "Rosemarie Gerstenberg",
        "Maria Wiecke",
        "Annette Ziellenbach",
        "Hanns Jörg Krumpholz",
        "Peter Schmitz",
        "Ernst Specht"
    ],
    "1987. Geheimagent Lennet und die Astronauten" => [
        "Rolf Schimpf",
        "Pierre Franckh",
        "Reinhard Glemnitz",
        "Alexander Allerson",
        "Leslie Fritz",
        "Herbert Weicker"
    ],
    "1987. Geheimagent Lennets erster Auftrag" => [
        "Rolf Schimpf",
        "Pierre Franckh",
        "Reinhard Glemnitz",
        "Sylvia Höbig",
        "Christian Marschall",
        "Michael Habeck"
    ],
    "1987. Hundeleben" => [
        "Daniel Kasztura",
        "Jan Eberwein",
        "Axel Milberg",
        "Margrit Carls",
        "Tilo Prückner",
        "Grete Wurm",
        "Jutta Graeb",
        "Marianne Lochert",
        "Siggi Schwientek",
        "Christiane Bachschmidt",
        "Jürgen Dluzniewski",
        "Paul Bürks",
        "Karl Renar",
        "Jan Groth",
        "Gerd Anthoff",
        "Evelyn Pielmeier",
        "Heide Simon",
        "Ellen Mahlke",
        "Thessy Kuhls"
    ],
    "1987. Zwillinge" => [
        "Donata Höffer",
        "Regina Lemnitz",
        "Günther-Maria Halmer",
        "Dietrich Mattausch"
    ],
    "1988. Der große Schluck" => [
        "Eva Ingeborg Scholz",
        "Ingrid Scherer",
        "Margit Spielmeyer",
        "Eva Garg"
    ],
    "1989. Der zwiefache Mann" => [
        "Holger Hagen",
        "Fritz Lichtenhahn",
        "Heinz Werner Kraehkamp",
        "Angelika Thomas",
        "Heinz Schubert",
        "Diether Krebs",
        "Werner Eichhorn",
        "Edgar Hoppe",
        "Pamela Freese",
        "Christine Dupuy",
        "Claudia Stump",
        "Johanna Gsell"
    ],
    "(NO YEAR) Briefe aus der Französischen Revolution" => [
        "Rolf Boysen",
        "Joachim Kerzel",
        "Jöns Anderson",
        "Gerhild Schüddekopp",
        "Marianne Kehlau",
        "Rosemarie Fendel",
        "Steffi Helmar",
        "Joachim Pukaß",
        "Klaus Stieringer"
    ],
    "1980. Komikercocktail" => [
        "Franz-Otto Krüger"
    ],
    "1990. Probelauf" => [
        "Gerd Baltus",
        "Carmen Renate Köper",
        "Werner Rundshagen",
        "Matthias Ponnier",
        "Erika Skrotzki",
        "Josef Meinertzhagen",
        "Bodo Primus",
        "Reinhard Schulat"
    ],
    "1990. Trambahn Hiroshima" => [
        "Rolf Schult",
        "Peter Lieck",
        "Ricarda Benndorf",
        "Evelyn Matzura",
        "Wolfgang Haubner",
        "Ruth Schiefenbusch",
        "Bernd Grawert",
        "Fritz Bachschmidt",
        "Camilo Briones",
        "Alexander von Mokos",
        "Oliver Kohns",
        "Norman Matt",
        "Aram Kaven"
    ],
    "1990. Zug um Zug" => [
        "Christian Berkel",
        "Claudia Roxane Barthel",
        "Friederike Wagner",
        "Friedhelm Ptok",
        "Christian Rode",
        "Klaus-Peter Grap",
        "Gerd Wameling",
        "Ute Rosenbauer",
        "Tilly Lauenstein"
    ],
    "1992. Arcturella" => [
        "Esther Hausmann",
        "Martin Umbach",
        "Bernd Stephan",
        "Detlef Kügow",
        "Harald Täschner",
        "Marc Schulze",
        "Christian Marschall",
        "Peter Weiss",
        "Hubert Mulzer",
        "Hertha Prunkl",
        "Wolf Euba",
        "Monika Weiß",
        "Achim Höppner",
        "Benedikt Fischer",
        "Wolf Euba",
        "Therese Asenstorfer"
    ],
    "1992. Die Bohrmaschine oder Warten auf Berlin" => [
        "Johanna Bassermann",
        "Otto Bolesch",
        "Andrea Kaiser",
        "Tilly Lauenstein",
        "Monica Bleibtreu"
    ],
    "1992. Für alle Länder" => [
        "Metin Uzumoglu",
        "Siir Eloglu",
        "Pinar Erincin",
        "Erol Sarp",
        "Cafer Cebe",
        "Fikri Sahim",
        "Evelyn Matzura",
        "Erwin Brunn",
        "Werner Brehm",
        "Lucius Woytt",
        "Wolf Aniol",
        "Zeljka Preksavec",
        "Andrea Mulle",
        "Gerhard Haag"
    ],
    "1992. Wohin" => [
        "Rolf Schult"
    ],
    "1993. Das unheimliche Dorf" => [
        "Hans Georg Panczak",
        "Michaela Mazac",
        "Claudius Zimmermann",
        "Christian Marschall",
        "Gerd Feller",
        "Marianne Jaitner",
        "Harald Dietl",
        "Jörg Maurer"
    ],
    "1993. Der Dialog" => [
        "Hildegard Kuhlenberg"
    ],
    "1993. Die Tatsachen im Fall Waldemar" => [
        "Thomas Holtzmann"
    ],
    "1993. Doktor Alzheimer bittet zu Tisch" => [
        "Fritz Lichtenhahn",
        "Rolf Schult",
        "Nina Danzeisen",
        "Marianne Rogée"
    ],
    "1993. Dreck" => [
        "Steve Karier"
    ],
    "1993. Zwei Fremde im Zug" => [
        "Peter Fricke",
        "Matthias Haase",
        "Jens Wawrczeck",
        "Esther Hausmann",
        "Yvonne Devrient",
        "Karin Schröder",
        "Wolfgang Höper",
        "Klaus Barner",
        "Joachim Jung",
        "Felix von Manteuffel",
        "Peter Rühring",
        "Karl-Heinz Butzen",
        "Helmut Wieland"
    ],
    "1994. Der heilige Antonius von Padua" => [
        "Rolf Schult"
    ],
    "1994. Verdi~ Würstchen und Verwirrung" => [
        "Cornelia Walter",
        "Maria Franziska Schüller",
        "Samy Orfgen",
        "Jochen Busse",
        "Werner Kroj",
        "Christian Krop",
        "Helga Bellinghausen",
        "Ursula Michelis"
    ],
    "1995. Das Radio der Zukunft" => [
        "Holger Czukay",
        "Valeri Scherstjanoi"
    ],
    "1995. Der Verbrecher" => [
        "Ulrich Faulhaber",
        "Lisa Kreuzer",
        "Konstantin Graudus",
        "Peter Fricke",
        "Angelika Bartsch",
        "Caroline Ebner",
        "Doris Plenert",
        "Martin Umbach",
        "Rolf Schult",
        "Ulrich Pleitgen",
        "Walter Renneisen",
        "Wolfgang Condrus",
        "Mechthild Großmann",
        "Klaus Mehrländer",
        "Regina Bode",
        "Laura Kuhr"
    ],
    "1995. Die Scheintoten" => [
        "Rosalinde Renn",
        "Michael Maassen",
        "Klaus Henner Russius",
        "Barbara Falter",
        "Siegfried Meisner",
        "Jodoc Seidel",
        "André Jung",
        "Nikola Weisse"
    ],
    "1996. Ariels Insel" => [
        "Matthias Leja",
        "Reinhard Schulat",
        "Claus Janzen",
        "Andreas Pietschmann",
        "Wolfgang Arps",
        "Joana Schümer",
        "Anja Niederfahrenhorst",
        "Rainer Delventhal",
        "Jacqueline Macaulay",
        "Sebastian Walch",
        "Manuela Alphons",
        "Rudolf Jürgen Bartsch",
        "Aljoscha Sebald",
        "Hansjoachim Krietsch"
    ],
    "1996. Stimmen" => [
        "Désirée Nosbusch",
        "Margot Busse",
        "Susann Thiede",
        "Götz Schulte",
        "Leslie Malton",
        "Christian Brückner",
        "Angelica Domröse",
        "Anna Böttcher",
        "Ruth Nimbach",
        "Rudolf Wessely",
        "Reiner Heise",
        "Elisabeth Trissenaar",
        "Klaus Herm",
        "Elke Petri",
        "Friedhelm Ptok",
        "Christoph Eichhorn",
        "Tilly Lauenstein",
        "Jürgen Hentsch",
        "Johannes Terne",
        "Thomas Thieme",
        "Réné Steinke",
        "Ulrike Krumbiegel",
        "Barbara Czerwinski"
    ],
    "1997. Die Frau und der Affe" => [
        "Anna Thalbach",
        "Werner Wölbern",
        "Christian Brückner",
        "Krista Posch",
        "Rolf Schult",
        "Heinz Meier",
        "Doris Wolters",
        "Gerhard Garbers",
        "Michael König",
        "Wolfgang Höper"
    ],
    "1997. Dr. Jekyll und Mr. Hyde" => [
        "Matthias Fuchs",
        "Rolf Schult",
        "Christoph Eichhorn",
        "Horst Bollmann",
        "Michael Habeck",
        "Friedhelm Ptok",
        "Christoph Zapatka",
        "Karin Buchali",
        "Daniel Bruehl",
        "Daniel Berger",
        "Alf Marholm",
        "Alexandra von Schwerin",
        "Jochen Kolenda",
        "Christine Urspruch",
        "Rudolf Jürgen Bartsch",
        "Reinhard Schulat",
        "Nele Hippe-Davis",
        "Malte Lauritz-Schrage",
        "Rolf Berg",
        "Thomas Klenk",
        "Christiane von Poelnitz"
    ],
    "1997. König Kleinbein und die Märchenkutsche" => [
        "Herbert Weicker",
        "Rudolf Wessely",
        "Michael Habeck",
        "Ines Buchmann",
        "Oliver Boysen",
        "Roman Dudler"
    ],
    "1997. Die Viruskonferenz" => [
        "Elisabeth Trissenaar",
        "Hilmar Thate",
        "Ulrich Wildgruber",
        "Erwin Steinhauer",
        "Theresa Hübchen",
        "Kota Morikawa",
        "Raida Melbiger-Younis",
        "Sintayehu Tsehay"
    ],
    "1998. talking exile" => [
        "Corinna Kirchhoff",
        "Dietmar Mues",
        "Brian Thomas"
    ],
    "1999. Der Weltensegler" => [
        "Herbert Weicker",
        "Susanna Bonasewicz",
        "Michael Pan",
        "Ernst Meincke",
        "Hans-Georg Panczak"
    ],
    "2002. Bitte folgen" => [
        "Nina Schopka",
        "Georg Mitterstieler",
        "Regina Lemnitz"
    ],
    "2002. Der Doppelgänger" => [
        "Ulrich Matthes",
        "Ignaz Kirchner",
        "Werner Wölbern"
    ],
    "2003. Ein perfekter Freund" => [
        "Boris Aljinovic",
        "Nicolette Krebitz",
        "Anne Moll",
        "Konstantin Graudus",
        "Erik Schäffler",
        "Rolf Becker",
        "Werner Wölbern",
        "Marc Zippel",
        "Hans Michael Kissing",
        "Lennart Krüger",
        "Gerhard Garbers",
        "Meike Harten",
        "Sonja Szylowicki",
        "Lena Stolze",
        "Sabine Falkenberg",
        "Emilio Castoldi",
        "Henning Venske",
        "Kerstin Hilbig"
    ],
    "2003. Hanns Eisler" => [
        "Angie Reed",
        "Nadja Petri",
        "Peter Gavajda",
        "Irm Hermann",
        "Josef Ostendorf",
        "Jens Rachut",
        "Schorsch Kamerun"
    ],
    "2003. Mühlheimers Experiment" => [
        "Torsten Ranft",
        "Gunda Aurich",
        "Cathlen Gawlich",
        "Horst Mendroch",
        "Martin Reinke"
    ],
    "2004. Sie & Er" => [
        "Martina Gedeck",
        "Roman Knizka",
        "Bernt Hahn",
        "Stephan Ullrich",
        "Ulrike Bliefert",
        "Gisela Claudius",
        "Horst Mendroch",
        "Roland Jamkowsky",
        "Christian Schramm",
        "Lukas Schreiber"
    ],
    "2005. Party im Blitz" => [
        "Peter Matić"
    ],
    "2005. Rekonstruktion Kresch" => [
        "Kurt Stieler",
        "Kurt Horwitz",
        "Willy Rösner",
        "Richard Häussler",
        "Fritz Straßner",
        "Rosemarie Bomhardt",
        "Thea Aichbichler",
        "Carl Wery",
        "Elfie Pertramer",
        "Ernst Barthels",
        "Heinrich Hauser",
        "Alfred Menhard",
        "Hans Baur",
        "Albert Wisheu",
        "Justin Lauterbach",
        "Heinz Beck",
        "Heinz Kargus",
        "Hanns Stein",
        "Marianne Brandt",
        "Albert Spenger",
        "August Riehl",
        "Rolf Möbius",
        "Rudolf Vogel",
        "Wastl Witt",
        "Carl Burg",
        "Georg Asow Peters",
        "Theodor Auzinger",
        "Maria Stadler",
        "Sepp Nigg",
        "Alwin Emmert",
        "Karl Schoepp",
        "Marianne Lankes",
        "Alfred Pongratz"
    ],
    "2006. Der Seuchenprinz" => [
        "Mila Dargies",
        "Ronald Henseler",
        "Yvon Jansen",
        "Daniel Lommatzsch",
        "Laila Oduro",
        "Josef Ostendorf",
        "Jens Rachut",
        "Laura Tonke",
        "Elisabeth Wöllert"
    ],
    "2006. Die Kinski-Bänder" => [
        "Klaus Kinski",
        "Lorenz Schröter"
    ],
    "2006. Mädchenzimmer mit Soldaten" => [
        "Laura Maire",
        "Mira Partecke",
        "Cathlen Gawlich",
        "Hüseyin Michael Cirpici",
        "Andreas Grothgar",
        "Gosia Konieczna",
        "Jens Wawrczeck"
    ],
    "2007. Gras wachsen hören" => [
        "Katharina Bihler",
        "Jan-Aiko zur Eck",
        "Gunter Cremer",
        "Gabriel Schlenstedt",
        "Johanna Dudek",
        "Susanne Freyler",
        "Michael Hanke"
    ],
    "2007. Hunter" => [
        "Bernhard Schütz",
        "Michele Cuciuffo",
        "Götz Argus",
        "Johanna Gastdorf",
        "Andreas Grothgar",
        "Isabel Mascarenhas",
        "Hüseyin Michael Cirpici",
        "Oliver Krietsch-Matzura",
        "Juan Carlos Lopez",
        "Volker Lippmann",
        "Jochen Langner",
        "Marion Minetti"
    ],
    "2008. Der Wind in den Weiden" => [
        "Alexandra Henkel",
        "Jan-Gregor Kremp",
        "Stefan Kaminski",
        "Siemen Rühaak",
        "Cathlen Gawlich",
        "Tommi Piper",
        "Horst Mendroch",
        "Heinz Baumeister",
        "Laura Maire",
        "Ernst August Schepmann",
        "Reiner Schöne",
        "Johanna Burg",
        "Bernd Kuschmann",
        "Marion Breckwoldt",
        "Johanna Burg",
        "Lilija Klee"
    ],
    "2008. Die Flüsterer" => [
        "Barnaby Metschurat",
        "Janina Sachau",
        "Carlo Ljubek",
        "Robert Gallinowski",
        "Walter Gontermann",
        "Michele Cuciuffo",
        "Roman Knizka",
        "Helene Grass",
        "Matthias Ponnier",
        "Hartmut Stanke",
        "Caroline Schreiber",
        "Johanna Burg",
        "Felicitas Stein",
        "Isis Krüger",
        "Gerd Rehse",
        "Philipp Sebastian",
        "Felix Meyer",
        "Eva Korte"
    ],
    "2008. Etwa 90 Grad" => [
        "Rainer Bock",
        "Mogens von Gadow",
        "Paul Herwig"
    ],
    "2008. Ländliche Küche in Zentralfrankreich" => [
        "Ulrich Matthes"
    ],
    "2009. Have You Ever Heard Of Wilhelm Reich" => [
        "Stefan Kastner",
        "Marcus Calvin",
        "Eva Löbau"
    ],
    "2009. Hildegard von Bingen" => [
        "Ilona Grandke"
    ],
    "2010. Das Judenauto" => [
        "Dieter Mann"
    ],
    "2010. Der Process" => [
        "Samuel Finzi",
        "Corinna Harfouch",
        "Jeanette Spassova",
        "Thomas Thieme",
        "Milan Peschel",
        "Manfred Zapatka",
        "Rufus Beck",
        "Jürgen Holtz"
    ],
    "2011. Der Zitherspieler" => [
        "Rainer Bock"
    ],
    "2011. Schwarzer Hund~ weißes Gras" => [
        "Vincent Leittersdorf",
        "Maria Kwiatkowsky",
        "Otto Mellies",
        "Kathrin Wehlisch",
        "Lars Rudolph",
        "Julian Mehne",
        "Andreas Leupold",
        "Carl Heinz Choynski"
    ],
    "2012. Die Entstehung des Hörspiels 'Umbach muß weg'" => [
        "Martin Umbach",
        "Kathrin von Steinburg",
        "Ilona Grandke",
        "Laura Maire",
        "Thomas von Steinaecker",
        "Philipp Götz",
        "Wilfried Hauer",
        "Beate Himmelstoß",
        "Oliver Mallison",
        "Wilhelm Manske",
        "Hemma Sophia Michel",
        "Heinz Peter",
        "Tommi Piper",
        "Sylvia Sperlich",
        "Andrea Wenzl",
        "Jay Rutledge"
    ],
    "2012. Elena weiß bescheid" => [
        "Doris Wolters",
        "Tatja Seibt",
        "Victoria Trauttmansdorff",
        "Bettina Hoppe",
        "Walter Renneisen",
        "Jochen Kolenda",
        "Georg Marin",
        "Matthias Haase",
        "Arved Birnbaum",
        "Claudia Mischke",
        "Hartmut Stanke",
        "Caroline Schreiber",
        "Roxana Samadi",
        "Jörg Hustiak"
    ],
    "2014. Das Ding im Nebel" => [
        "Alexander Hauff",
        "Konstantin Lindhorst",
        "Marc Benjamin Puch",
        "Lucie Heinze",
        "Peter Gilbert Cotton",
        "Winfried Peter Goos",
        "Michael Evers",
        "Gisbert-Peter Terhorst",
        "Anne Kanis",
        "Jürgen Mai"
    ],
    "2014. Das Erfinden der Liebe" => [
        "Samuel Weiss",
        "Martin Bross",
        "Marie-Lou Sellem",
        "Manuel Volker Risch",
        "Vittorio Alfieri",
        "Daniel Berger",
        "Sigrid Burkholder",
        "Oliver Krietsch-Matzura",
        "Jochen Lagner",
        "Andreas Laurenz Maier",
        "Rainer Homann"
    ],
    "2014. Turing Bytes" => [
        "Larissa Aimee Breidbach",
        "Louis Friedemann Thiele",
        "Ilse Strambowski",
        "Svenja Wasser",
        "Torsten Peter Schnick",
        "Silke Linderhaus",
        "Jochen Langner",
        "Bruno Tendera",
        "Patrizia Wapinska",
        "Jean Paul Baeck",
        "Rainer Delventhal",
        "Hartmut Stanke",
        "Tom Jacobs",
        "Constance Craemer"
    ],
    "2015. Frau Higgins" => [
        "Irm Hermann",
        "Jodoc Seidel",
        "Jessica Higgins",
        "Klaus Brömmelmeier",
        "Thomas Mathys"
    ],
    "2016. Untergang des Abendlandes" => [
        "Sascha Icks",
        "Matthias Haase",
        "Hedi Kriegeskotte",
        "Stefan Wilkening",
        "Martin Bross"
    ],
    "2017. Der römische Dolch" => [
        "Arnd Klawitter",
        "Cathlen Gawlich",
        "Wolf-Dietrich Sprenger",
        "Roman Knižka",
        "Uta Hallant",
        "Martin Engler",
        "Monika Oschek",
        "Steffen C. Jürgens",
        "Gerd Grasse",
        "Petra Wolf",
        "Udo Kroschwald",
        "Axel Wandtke",
        "Adriana Altaras",
        "Barbara Becker"
    ],
    "2017. Industrie und Glück" => [
        "Ronel Doual",
        "Andrea Huyoff",
        "Tian Rotteveel",
        "Johannes Frick",
        "Anna Zett",
        "Jochen Jezussek"
    ],
    "2017. Nach Mitternacht" => [
        "Lisa Wagner",
        "Thomas Wodianka",
        "Jan Andreesen",
        "Magda Czogalla",
        "Martin Engler",
        "Gerd Grasse",
        "Hans Peter Hallwachs",
        "Britta Steffenhagen",
        "Stephanie Eidt",
        "Stefan Mehren",
        "Peter Moltzen",
        "Catherine Stoyan",
        "Ilka Teichmüller",
        "Barbara Meerkötter"
    ],
    "2017. Pornflakes" => [
        "Friederike Kempter",
        "Isabelle Höpfner",
        "Denis Moschitto",
        "Daniel Wiemer",
        "Patrick Bach",
        "Robert Dölle",
        "Arnd Klawitter",
        "Patrick Mölleken",
        "Camilla Renschke",
        "Lars Rudolph",
        "Edda Fischer",
        "Leonie Renée Klein",
        "Ulrich Haß",
        "Ilse Strambowski",
        "Stuart Kummer"
    ],
    "2019. Die Gesänge der Raumfahrer" => [
        "Matthias Bundschuh",
        "Anne Müller",
        "Maria Hartmann",
        "Martin Engler",
        "Michael Rotschopf",
        "Tilla Kratochwil",
        "Bettina Kurth",
        "Walter Kreye"
    ],
    "2019. EXIT" => [
        "Anna Schudt",
        "Kathleen Morgeneyer",
        "Stefan Konarske"
    ],
    "2020. Hegels Hund" => [
        "Ulrich Noethen",
        "Heinrich Giskes",
        "Nikolaus Benda",
        "Georg Marin",
        "Axel Gottschick",
        "Dorkas Kiefer",
        "Julia Karl",
        "Juliane Ledwoch"
    ],
    "2020. Verfahren" => [
        "Graham F. Valentine",
        "Meriam Abbas",
        "Astrid Meyerfeldt",
        "Fabian Hinrichs",
        "Jan Krauter",
        "Victoria von Trauttmansdorff",
        "Serkan Kaya"
    ],
    "2021. Briefe aus der Hölle" => [
        "Martin Engler",
        "Tonio Arango",
        "Robert Gallinowski",
        "Patrick Güldenberg",
        "Matthias Bundschuh",
        "Wolfram Koch",
        "Nina Ernst",
        "Andreas Kilian"
    ],
    "2021. Dissipatio humani generis" => [
        "Thiemo Strutzenberger"
    ],
    "2021. Endstation Deutsche Sehnsucht" => [
        "Anaïs Urban",
        "Martha von Mechow",
        "Nathalie Seiß",
        "Kerstin Grassmann"
    ],
    "2021. Hier ist noch alles möglich" => [
        "Henni Jörissen",
        "Michael Neuenschwander",
        "Sven Schelker",
        "Thomas Douglas",
        "Bodo Krumwiede",
        "Inga Eickemeier"
    ],
    "2021. Hotel C" => [
        "Martin Engler"
    ],
    "2021. Imani" => [
        "Nico Holonics"
    ],
    "2022. Albert Einstein~ Sigmund Freud - Warum Krieg" => [
        "Antonio Pellegrino"
    ],
    "2022. Animate" => [
        "Judith Rosmair",
        "Steve Karier"
    ],
    "2022. Cryptos" => [
        "Elisa Schlott",
        "Jonas Nay",
        "Jannik Schümann",
        "Dietrich Hollinderbäumer",
        "Katharina Leonore Goebel"
    ],
    "2022. Der Termin" => [
        "Hannah Schutsch",
        "Tilman Strauss",
        "Franziska Machens",
        "Dor Aloni",
        "Camill Jammal"
    ],
    "2022. Die Irrfahrten des Sergej Sergejewitsch" => [
        "Svetlana Belesova",
        "André Kaczmarczyk",
        "Sonja Beißwenger",
        "Kilian Land",
        "Lucian Plessner",
        "Steven Scharf",
        "Wolf-Dietrich Sprenger",
        "Aljoscha Stadelmann",
        "Merle Wasmuth"
    ],
    "2022. Klappersteine" => [
        "Cristin König",
        "Denis Geyersbach"
    ],
    "2022. Picknick im Dunkeln" => [
        "Jean-Pierre Cornu",
        "Samuel Weiss"
    ]
];
