<?php

return [
    "1946. Fräulein Else" => [
        "Gerd Ribatis",
        "Irmgard Weyrather",
        "Anette Roland",
        "Ernst Sladeck",
        "Ludwig Baschang",
        "Ursula Zache",
        "Lieselotte Bellert",
        "Günther Vulpius",
        "Hans Goguel",
        "Eva Fiebig",
        "Horst Uhse",
        "Karl Kempf",
        "Lothar Hartmann"
    ],
    "1948. Draußen vor der Tür" => [
        "Hanns Stein",
        "Marianne Kehlau",
        "Ernst Schlott",
        "Klaus W. Krause",
        "Fred Kallmann",
        "Else Quecke",
        "Rudolf Helten",
        "Else Wolz",
        "Karl Burg",
        "August Riehl",
        "Gertrud Spalke",
        "Anneliese Schmidt"
    ],
    "1951. Der Hauptmann von Köpenick" => [
        "Heinz Schimmelpfennig",
        "Ernst Sladeck",
        "Kurt Lieck",
        "Max Mairich",
        "Hanns Bernhardt",
        "Horst Beilke",
        "Wolfgang Golisch",
        "Alexander Zawadski",
        "Margot Müller",
        "Günther Gube",
        "Wolfgang Regentrop",
        "Ernst Ehlert",
        "Wolfgang Jarnach",
        "Paul Dättel",
        "Georg Lehn",
        "Alois Garg",
        "Arno Ebert",
        "Hans Günther",
        "Rudolf Köppler",
        "Stephanie Wiesand",
        "Evelyn Siebert",
        "Walter Kiesler",
        "Kurt Ebbinghaus",
        "Bernd Schorlemer",
        "Johannes Sendler",
        "Georg Michael",
        "Hans Timerding",
        "Alexander Hegarth",
        "Hans Günther",
        "Benno Schurr",
        "Ernst Kiefer",
        "Wolfgang von Rotberg",
        "Klaus Friedrich",
        "Otto Ernst Lundt",
        "Heinz Born"
    ],
    "1951. Träume" => [
        "Erich Schellow",
        "Annegret Lerche",
        "Heinz Piper",
        "Cay Dietrich Voss",
        "Eduard Marks",
        "Lotte Klein",
        "Wolfgang Rottsieper",
        "Jo Wegener",
        "Karin Lunau",
        "Max Walter Sieg",
        "Louise Dorsay",
        "Helmuth Gmelin",
        "Inge Schmidt",
        "Dieter Döderlein",
        "Herbert A. E. Böhme",
        "Maria Janke",
        "Inge Meysel",
        "Michael Becker",
        "Ursula Pietsch",
        "Helmut Peine",
        "Hermann Kneer",
        "Gerd Martienzen",
        "Richard Münch",
        "Heinz Suchantke",
        "Josef Dahmen",
        "Mirjam Horwitz",
        "Dagmar Altrichter",
        "Dietrich Haugk",
        "Wilhelm Kürten"
    ],
    "1953. Bruder an der Pforte" => [
        "Kurt Stieler",
        "Kurt Horwitz",
        "Willy Rösner",
        "Richard Häussler",
        "Fritz Straßner",
        "Rosemarie Bomhardt",
        "Thea Aichbichler",
        "Carl Wery",
        "Elfie Pertramer",
        "Ernst Barthels",
        "Heinrich Hauser",
        "Alfred Menhard",
        "Hans Baur",
        "Albert Wisheu",
        "Justin Lauterbach",
        "Heinz Beck",
        "Heinz Kargus",
        "Hanns Stein",
        "Marianne Brandt",
        "Albert Spenger",
        "August Riehl",
        "Rolf Möbius",
        "Rudolf Vogel",
        "Wastl Witt",
        "Carl Burg",
        "Georg Asow Peters",
        "Theodor Auzinger",
        "Maria Stadler",
        "Sepp Nigg",
        "Alwin Emmert",
        "Karl Schoepp",
        "Marianne Lankes",
        "Alfred Pongratz"
    ],
    "1953. Der Idiot" => [
        "Erik Schumann",
        "René Deltgen",
        "Xenia Hegmann",
        "Fritz Saalfeld",
        "Angelika Aurel",
        "Christa Keller",
        "Arno Assmann",
        "Otto Rouvel",
        "Walter Griesmann",
        "Bogislav von Heyden",
        "Käte Jaenicke",
        "Ludwig Kepper",
        "Lieselotte Koch",
        "Antonie Schön-Siener",
        "Hansgeorg Neubert",
        "Hilde Nocker",
        "Christian Schmieder",
        "Aly Wunsch"
    ],
    "1954. Der Hauptmann von Köpenick" => [
        "Hans-Reinhard Müller",
        "Paul Bildt",
        "Friedrich Domin",
        "Erika Riemann",
        "Ursula Kube",
        "Werner Hinz",
        "Charlotte Witthauer",
        "Hans Drahn",
        "Heinz Leo Fischer",
        "Fritz Benscher",
        "Hans Leibelt",
        "Wolfried Lier",
        "Jaspar von Oertzen",
        "Ernst Fritz Fürbringer"
    ],
    "1954. Der Jäger von Fall" => [
        "Hans Baur",
        "Adele Hoffmann",
        "Rolf Castell",
        "Erich Auer",
        "Ida Schumacher",
        "Ingeborg Wutz",
        "Grete Schorn",
        "Gusti Kreissl",
        "Wastl Witt",
        "Franz Fröhlich",
        "Hans Seitz",
        "Fritz Straßner",
        "Franz Loskarn"
    ],
    "1954. Unter dem Milchwald" => [
        "Gisela von Collande",
        "Paul Bildt",
        "Heinz Sailer",
        "Herbert A. E. Böhme",
        "Ilse Bally",
        "Inge Meysel",
        "Fritz Wagner",
        "Elly Burgmer",
        "Edda Seippel",
        "Ruth Hellberg",
        "Heinz Klevenow",
        "Lotte Brackebusch",
        "Rudolf Fenner",
        "Ludwig Cremer",
        "Dietrich Haugk",
        "Helga Bammert",
        "Manfred Greve",
        "Kornelia Boje",
        "Paul C. Klose",
        "Manfred Steffen",
        "Bammert Junior",
        "Liselotte Willführ",
        "Krafft-Georg Schulze",
        "Anna Blask",
        "Ernst Rottluff",
        "Erna Nitter",
        "Horst Beck",
        "Hermann Kner",
        "Kurt Klopsch",
        "Jo Wegener",
        "Dorothea Moritz",
        "Max Zawislak",
        "Heinz Roggenkamp",
        "Adolf Hansen",
        "Josef Dahmen",
        "Werner Rundshagen",
        "Charlotte Schellenberg",
        "Karen Hüttmann",
        "Helmut Peine",
        "Alexander Hunzinger",
        "Charlotte Kramm",
        "Hermann Beyer",
        "Lotte Klein",
        "Wolfgang Rottsieper",
        "Eric Schildkraut",
        "Helmuth Gmelin",
        "Marga Maasberg",
        "Imme Froh",
        "Ingeborg Spiegel",
        "Vera Schult",
        "Vera Gruber",
        "Ingrid von Bothmer",
        "Ursula Noack",
        "Ursula von Bose",
        "Liselotte Kunze",
        "Inge Fabricius",
        "Barbara Uhsadel",
        "Eva Portmann",
        "Eva Fiebig",
        "Maria Martienzen",
        "Andreas von der Meden"
    ],
    "1954. Zonengrenzbus Helmstedt" => [
        "Robert Klupp",
        "Marianne Dohm-Franke",
        "Herbert Stass",
        "Margarete Schön",
        "Paula Paulsen",
        "Albert Johannes",
        "Klaus Herm",
        "Kurt Buecheler",
        "Eduard Wandrey",
        "Reinhold Bernt",
        "Arthur Jaschke",
        "Edzard Bruns",
        "Anneliese Priefert",
        "Harry Wüstenhagen",
        "Edgar Ott",
        "Horst Keitel",
        "Clemens Hasse",
        "Horst Niendorf",
        "Hermann Wagner"
    ],
    "1955. Der sechste Gesang" => [
        "Mathias Wieman",
        "Will Quadflieg",
        "Ellen Schwiers",
        "Kaspar Brüninghaus",
        "Joachim Teege",
        "Gisela Zoch",
        "Kurt Ebbinghaus",
        "Ann Höling",
        "Walter Richter",
        "Trude Tandar",
        "Walter Starz",
        "Peter Esser",
        "Jürgen Goslar",
        "Werner Hinz",
        "Elfriede Kuzmany",
        "Otto Collin",
        "Erich Buschardt",
        "Hans Helmut Dickow",
        "Ernst Ehlert",
        "Horst Frank",
        "Ulrich Goetsch",
        "Heinz Lück",
        "Hans Mahnke",
        "Robert Rathke",
        "Rudolf Rhomberg",
        "Helene Richter-Mielich",
        "Rudolf Siege",
        "Ernst Sladeck",
        "Wolfgang Schwarz",
        "Hariolf Schwerdt",
        "Walter Starz",
        "Gert Tellkampf"
    ],
    "1956. Das Fräulein von Scuderi" => [
        "Ida Ehre",
        "Wera Petersohn",
        "Walter Schmidinger",
        "Wilhelm Pilgram",
        "Romuald Pekny",
        "Johanna Koch-Bauer",
        "Harry Grüneke"
    ],
    "1956. Der Monopteros" => [
        "Liesl Karlstadt",
        "Irene Kohl",
        "Thea Aichbichler",
        "Barbara Gallauner",
        "Michl Lang",
        "Heinz Leo Fischer",
        "Franz Fröhlich",
        "Peter Timm Schaufuß",
        "Heinrich Hauser",
        "Fred Kallmann",
        "Horst Reichel",
        "Gerhard Eigelsperger"
    ],
    "1956. Unterm Birnbaum" => [
        "René Deltgen",
        "Ursula von Reibnitz",
        "Erwin Kleist",
        "Marta Ferber",
        "Ludwig Thiesen",
        "Walter Richter",
        "Wilhelm Pilgram",
        "Horst Beilke",
        "Alwin Joachim Meyer",
        "Heinz Schacht",
        "Hildegard Jacob",
        "Kaspar Brüninghaus",
        "Lilly Towska",
        "Arthur Mentz",
        "Karl Brückel",
        "Rudolf Therkatz",
        "Harry Grüneke",
        "Ruth Pera",
        "Brigitte Lebaan",
        "Kurt Beck"
    ],
    "1957. Phädra" => [
        "Gert Westphal",
        "Hilde Krahl",
        "Klausjürgen Wussow",
        "Gisela Zoch",
        "Ludwig Anschütz",
        "Lina Carstens",
        "Ursula Langrock",
        "Henny Schneider-Wenzel"
    ],
    "1958. Der gute Gott von Manhattan" => [
        "Ernst Schröder",
        "Horst Frank",
        "Fritz Schröder-Jahn",
        "Margrit Ensinger",
        "Hans Clarin",
        "Karl Lieffen",
        "Anja Buczkowski",
        "Mario Adorf",
        "Adalbert von Cortens",
        "Gustl Datz",
        "H. Wolfgang Zeiger",
        "Rainer Loose",
        "Ilva Günten",
        "Hans Quitschorra",
        "Nils Clausnitzer",
        "Horst Raspe",
        "Ursula Kube",
        "Alexander Malachovsky",
        "Leo Bardischewski",
        "Bettina Braun",
        "Elli Haase",
        "Hartmut Friedrich"
    ],
    "1958. Garou-Garou" => [
        "Peter Lühr",
        "Erich Ponto",
        "Ernst Schlott",
        "Hans Herrmann-Schaufuß",
        "Paul Hoffmann",
        "Bruno Hübner",
        "Siegfried Lowitz",
        "Fred Kallmann",
        "Ernst Rotmund",
        "Bum Krüger",
        "Trude Hesterberg",
        "Walter Hilbring",
        "Hilde Classen",
        "Christian Marschall",
        "Ingeborg Hoffmann",
        "Horst Raspe",
        "Leo Bardischewski"
    ],
    "1958. Hermann und Dorothea" => [
        "Rolf Schult",
        "Dinah Hinz",
        "Otto Rouvel",
        "Gerda Maurus",
        "Peter Esser",
        "Rudolf Therkatz",
        "Claus Clausen",
        "Bernhard Minetti"
    ],
    "1958. Prinz Friedrich von Homburg" => [
        "Mila Kopp",
        "P. Walter Jacob",
        "Margot Franken",
        "Kurt Haars",
        "Rolf Schult",
        "Hans Mahnke",
        "Harald Baender",
        "Ludwig Anschütz",
        "Hans Georg Laubenthal",
        "Herbert Steinmetz",
        "Kurt Norgall",
        "Werner Bruhns",
        "Alf Tamin",
        "Peter H. Schwerdt",
        "Gertrud Habel",
        "Hans Treichler",
        "Rolf Schimpf",
        "Fred Goebel",
        "Karl Grytzmann",
        "Fred C. Siebeck"
    ],
    "1958. Zwei alte Damen feuern" => [
        "Agnes Windeck",
        "Else Ehser",
        "Arthur Schröder",
        "Leopold Rudolf",
        "Ada Lübben",
        "Helmut Ahner",
        "Otto Czarski",
        "Herbert Weissbach",
        "Harry Wüstenhagen",
        "Sigrid Lagemann",
        "Herbert Wilk",
        "Tosca Dohnke",
        "Heinz Giese",
        "Otto Braml",
        "Otto Stoeckel",
        "Ernst Sattler",
        "Theodor Rocholl",
        "Joachim Boldt",
        "Wolfgang Conradi",
        "Manfred Meurer",
        "Paul Paulschmidt",
        "Wolfgang Schill",
        "Friedmar Wehner",
        "Alexander Welbat",
        "Peter Uwe Witt"
    ],
    "1959. Don Juan" => [
        "Will Quadflieg",
        "Kurt Stieler",
        "Maria Becker",
        "Heinz Klingenberg",
        "Helmut Janatsch",
        "Kurt Sowinetz",
        "Hans Putz",
        "Gisela Zoch",
        "Cornelia Oberkogler",
        "Wolfgang Hebenstreith",
        "Ernst Ginsberg",
        "Kurt Weinzierl",
        "Klaus Gmeiner",
        "Victor Braun",
        "Kurt Ebbinghaus"
    ],
    "1959. Kabale und Liebe" => [
        "Renate Schroeter",
        "Peter Lieck",
        "Hans Hessling",
        "Kurt Horwitz",
        "Fritz Schröder-Jahn",
        "Ernst Ronnecker",
        "Ellen Schwiers"
    ],
    "1959. Mr. Deeds in New York" => [
        "Peer Schmidt",
        "Irene Marhold",
        "Hilde Hildebrandt",
        "Luitgard Im",
        "Olga von Togni",
        "Enzo Kalani",
        "Richard Bohne",
        "Hans Dieter Zeidler",
        "Walter Grüters",
        "Armas Sten Fühler",
        "Lieselotte Bettin",
        "Joachim Engel-Denis",
        "Günter Pfitzmann",
        "Gerhard Ritter",
        "Kurt Heinz Welke",
        "Werner Xandry",
        "Georg-Lars Doddenhof",
        "Heinz Stoewer",
        "Thomas Fabian",
        "Maria Madlen Madsen",
        "Joachim Schweighöfer",
        "Robert Seibert"
    ],
    "1960. Der Doppelgänger" => [
        "Friedrich Dürrenmatt",
        "Gustav Burmester",
        "Siegfried Wischnewski",
        "Hanns Ernst Jäger",
        "Anneliese Römer",
        "Karen Hüttmann"
    ],
    "1960. Korczak und die Kinder" => [
        "Hans Korte",
        "Hans Stetter",
        "Wolfgang Schirlitz",
        "Gisela Fischer",
        "Jürgen Lang",
        "Josef Matak"
    ],
    "1960. Nacht über Dublin" => [
        "Rolf Becker",
        "Pinkas Braun",
        "Kurt Ebbinghaus",
        "Robert Graf",
        "Herbert Fleischmann",
        "Hans-Martin Koettenich",
        "Charlotte Joeres",
        "Hans Mahnke",
        "Anita Mey",
        "Lola Müthel",
        "Helga Thiem-Mietzner",
        "Herbert Wilk"
    ],
    "1960. Peter Voss - Der Millionendieb" => [
        "Arno Assmann",
        "Ingrid Pan",
        "Günter Pfitzmann",
        "Herbert Kroll",
        "Alfons Teuber",
        "Gustl Datz",
        "Wolf Petersen",
        "Gernot Duda",
        "Gustl Weishappel",
        "Hans Nielsen",
        "Klaus Havenstein",
        "Ulrich Beiger",
        "Josef Sieger",
        "Helmut Haupt",
        "Michael Block",
        "Kurt Marquardt",
        "Hans Dieter Zeidler",
        "Helmut Haupt",
        "Rudolf Neumann",
        "Hansjörg Fröhlich",
        "Günter Lynen",
        "Senta Bonneval",
        "Marlies Compère",
        "Franziska Bronnen",
        "Christl Schmidt",
        "Willi Krüger",
        "Anton Reimer",
        "Werner Hessenland",
        "Sidon Sindelar",
        "Fritz Rasp",
        "Eva L'Arronge",
        "Rolf Castell",
        "Fritz Strassner",
        "Leo Siedler",
        "Hans Baur",
        "Wolfried Lier",
        "Franz Fröhlich",
        "Hans Stadtmüller",
        "Rudolf Rhomberg",
        "Heini Göbel",
        "Hans Pössenbacher",
        "Joachim Müller",
        "Walter Holten",
        "Franz Fröhlich",
        "Wolfgang Eichberger",
        "Adolf Ziegler",
        "Paul Bös",
        "Armando Semaforo",
        "Ernst Stankovski",
        "Franz Schafheitlin",
        "Michael von Block",
        "Jochen Hauer",
        "Dunja Movar",
        "Panos Papadopulos",
        "Dietrich Thoms",
        "Konrad Georg",
        "Konrad Georg",
        "Günter Gräwert",
        "Werner Uschkurat",
        "Horst Tappert",
        "Herbert Kroll",
        "Trude Breitschopf",
        "Hans Joachim Quitschorra",
        "Hans Jürgen Fröhlich"
    ],
    "1961. Der blaue Vogel" => [
        "Matthias Fuchs",
        "Cordula Trantow",
        "Ulrich Beiger",
        "Wolf Ackva",
        "Claudia Bethge",
        "Alois Maria Giani",
        "Karl Michael Vogler"
    ],
    "1961. Die letzten Tage des Königs" => [
        "Robert Lindner",
        "Fritz Rasp",
        "Hans Fitz",
        "Walter Holten",
        "Friedrich Domin",
        "Lina Carstens",
        "Hans Baur",
        "Willy Rösner",
        "Rosemarie Noris-Bomhardt",
        "Ulrich Beiger",
        "Karl Hanft",
        "Bruno Hübner",
        "Ernst Schlott",
        "Ludwig Schmid-Wildy",
        "Uli Steigberg",
        "Hans Stein",
        "Fritz Strassner"
    ],
    "1961. Die Morgenröte" => [
        "Helen Vita",
        "Fritz Straßner",
        "Ferdinand Anton",
        "Charlotte von Bomhard",
        "Luise Deschauer",
        "Hanns Ernst Jäger",
        "Walter Holten",
        "Karl-Michael Vogler",
        "Paul Kürzinger",
        "Ludwig Schmid-Wildy",
        "Helmut Fischer",
        "Gustl Weishappel",
        "Ernst Barthels",
        "Hans Eichleiter",
        "Helmut Haupt",
        "Franz Loskarn",
        "Alexander Malachovsky",
        "Erich Neureuther",
        "Wolf Petersen",
        "Albert Wisheu"
    ],
    "1961. Die rote Herberge" => [
        "Christoph Bantzer",
        "Rolf Becker",
        "Rudolf Birkemeyer",
        "Lars Doddenhof",
        "Josef Eschenbrücher",
        "Rosemarie Gerstenberg",
        "Kurt Haars",
        "Maria Häussler",
        "Heide Joram",
        "Dieter Kurz",
        "Maria Madlen Madsen",
        "Robert Meyn",
        "Karl-Heinz Peters",
        "Günther Schramm",
        "Robert Seibert",
        "Heinz Stoewer",
        "Gisela Vesco",
        "Werner Xandry"
    ],
    "1961. Maigret" => [
        "Paul Dahlke",
        "Erik Schumann",
        "Uli Steigberg",
        "Fritz Strassner",
        "Erwin Faber",
        "Bum Krüger",
        "Max Mairich",
        "Eva L'Arronge",
        "Wolf Ackva",
        "Klausjürgen Wussow",
        "Annemarie Holtz",
        "Eva-Maria Bauer",
        "Benno Sterzenbach",
        "Rudolf Rhomberg",
        "Paul Bürks",
        "Gustl Weishappel",
        "Sid Sindelar-Brecht",
        "Elmar Wepper",
        "Konrad Georg",
        "Jochen Hauer",
        "Michael Block",
        "Hanna Burgwitz",
        "Marlies Compère",
        "Senta Bonneval",
        "Stefanie Fricke",
        "Helmut Haupt",
        "James von Berlepsch",
        "Josef Seeber",
        "Traute Rose",
        "Heini Goebel",
        "Reinhard Glemnitz",
        "Rolf Boysen",
        "Albert Hehn",
        "Klaus W. Krause",
        "Gernot Duda",
        "Hans Eichleiter",
        "Hanne Wieder",
        "Hans Clarin",
        "Hanns Ernst Jäger",
        "Gertrud Spalke",
        "Eva Maria Kleinschmidt",
        "Herta Worell",
        "Trude Breitschopf",
        "Erich Neureuther",
        "Alexander Malachovsky",
        "Paul Bös",
        "Reinhard Glemnitz",
        "Bum Krüger",
        "Robert Klupp",
        "Fritz Wilm Wallenborn",
        "Kurt Marquardt",
        "Konrad Georg",
        "Otto Brüggemann",
        "Michael Lenz",
        "Lis Verhoeven",
        "Helen Vita",
        "Elfe Gerhart",
        "Anton Reimer",
        "Rotraut Grauer",
        "Claudia Bethge",
        "Addi Adametz",
        "Hans Elwenspoek",
        "Sid Sindelar-Brecht",
        "Wolfgang Eichberger",
        "Elmar Wepper",
        "Alexander Malachovsky",
        "Robert Neumann",
        "Helmut Haupt",
        "Dieter Seulen",
        "Heidi Fuchs",
        "Bernd Steinseiffer",
        "Wolfgang Reichmann",
        "Horst Frank",
        "Ingrid van Bergen",
        "Thomas Braut",
        "Dorothea Gmelin",
        "Lisa Hellwig",
        "Ursula Kube",
        "Hermann Göbel",
        "Hans Eichleiter",
        "Elmar Wepper",
        "Robert Klupp",
        "Josef Manoth",
        "Werner Uschkurat",
        "Marlies Compère",
        "Stefanie Fricke",
        "Eva Maria Theilich",
        "Uta Schwinn",
        "Helmut Haupt",
        "Rudolf Neumann",
        "Dieter Jaddatz",
        "Dieter Seulen"
    ],
    "1961. Paul Temple" => [
        "Kurt Marquardt",
        "Karl John",
        "Rosemarie Fendel",
        "Fritz Straßner",
        "Adolf Ziegler",
        "Horst Tappert",
        "Inge Birkmann",
        "Jürgen Arndt",
        "Heidi Brühl",
        "Fritz Wilm Wallenborn",
        "Leo Bardischewski",
        "Jürgen Goslar",
        "Renate Grosser",
        "Eva Vaitl",
        "Ellinor von Wallerstein",
        "Jochen Hauer",
        "Ernst Ginsberg",
        "Hans Cossy",
        "Alexander Malachovsky",
        "Horst Tappert",
        "Karl Czerny",
        "Eleonore Noelle",
        "Inge Schulz",
        "John Pauls-Harding",
        "Erik Jelde",
        "Erwin Faber",
        "Klaus W. Krause",
        "Wolfgang Büttner",
        "Erik Jelde",
        "Wolfgang Bekh",
        "Hilde Berndt"
    ],
    "1962. 3. Die Unsichtbaren Krallen des Dr. Mabuse" => [
        "Wolf Frass",
        "Gert Günther Hoffmann",
        "Karin Dor",
        "Siegfried Lowitz",
        "Walo Lüönd",
        "Rudolf Fernau",
        "Kurd Pieritz",
        "Werner Peters",
        "Wolfgang Preiss"
    ],
    "1962. Fuhrmann Henschel" => [
        "Leopold Biberti",
        "Curt Bock",
        "Borek",
        "Willy Buser",
        "Hans Caninenberg",
        "Agnes Delsarto",
        "Helga Feddersen",
        "Rudolf Hofmann",
        "Christa Keller",
        "Otto Mächtlinger",
        "Walter Richter",
        "Eric Schildkraut",
        "Ingeborg Stein",
        "Armin W. Suessenguth",
        "Ulrich Lauterbach"
    ],
    "1962. Rashomon" => [
        "Kurt Lieck",
        "Robert Rathke",
        "Hannes Tannert",
        "Heinz Rabe",
        "Clara Walbröhl",
        "Wolfgang Reichmann",
        "Inge Bahr",
        "Gert Westphal"
    ],
    "1962. Terra Incognita" => [
        "Horst Tappert",
        "Heinz Schimmelpfennig",
        "Albert Carl Weiland",
        "Marlies Schoenau",
        "Peter Lühr",
        "Nora Minor",
        "Wolfgang Dörich",
        "Josef Sieber",
        "Richard Kley",
        "Karl-Michael Vogler",
        "Paul Bös",
        "Claudia Bethge",
        "Erro Wacker",
        "Robert Klupp",
        "Michael Gaffron",
        "Peter Capell",
        "Erwin Faber",
        "Ado Riegler",
        "Hans Joachim Quitschorra",
        "Uli Steigberg",
        "Reinhard Glemnitz",
        "Hans Zesch-Ballot",
        "Georg Lehn",
        "Fritz Schmiedel",
        "Gerhard Lippert",
        "Harald Drechler",
        "Richard Kley",
        "Kurt Sterneck",
        "Ingeborg Wutz",
        "Edgar Mandel",
        "Leo Siedler",
        "Kurt Sterneck",
        "Konrad Georg",
        "Helmuth Haupt",
        "Marlies Compère"
    ],
    "1963. Memoiren eines Butlers" => [
        "Theo Lingen",
        "Peter Pasetti",
        "Gustav Knuth",
        "Martin Benrath",
        "Hanne Wieder",
        "Norbert Kappen",
        "Hans Clarin",
        "Heini Göbel",
        "Anton Reimer",
        "Anders",
        "Heinz-Günter Stamm",
        "Josef Seeber"
    ],
    "1963. Simplicius Simplicissimus Teutsch" => [
        "Hans Clarin",
        "Harry Grüneke",
        "Max Noack",
        "Gerhard Becker",
        "Rolf Schult",
        "Hermann Schomberg",
        "Hanns Ernst Jäger",
        "Kurt Ehrhardt",
        "Frank Barufski",
        "Wolf Schlamminger",
        "Herbert Hennies",
        "Hans Georg Gregor",
        "Curt Faber",
        "Alois Garg",
        "Ingeborg Schlegel",
        "Marianne Rogee",
        "Wolfgang Forester",
        "Manfred Georg Herrmann",
        "Wolfgang Forester",
        "Dorothea Moritz",
        "Kaspar Brüninghaus",
        "Kurt Lieck",
        "Ludwig Thiesen",
        "Magda Hennings",
        "Alwin Joachim Meyer",
        "Karl-Maria Schley",
        "Helmut Peine",
        "Rudolf Rhomberg",
        "Wilhelm Pilgram",
        "Trude Meinz",
        "Brigitte Lebaan",
        "Harry Grüneke",
        "Erna Grossmann"
    ],
    "1963. Verwundet" => [
        "Hannes Messemer",
        "Günther Neutze",
        "Irmgard Först",
        "Elfriede Rückert",
        "Marianne Rogée",
        "Magda Hennings",
        "Brigitte Lebaan",
        "Steffy Helmar",
        "Klaus-Dieter Pittrich",
        "Fred Maire",
        "Anton Ippen",
        "Harald Meister",
        "Manfred Idem"
    ],
    "1964. 1913" => [
        "Ernst Schröder",
        "Ernst Stankovski",
        "Regine Lutz",
        "Gisela Uhlen",
        "Hubert Suschka",
        "Joachim Teege",
        "Heinz Baumann",
        "Georg Kostya",
        "E. O. Fuhrmann",
        "Friedrich Maurer",
        "Ernst Barthels"
    ],
    "1964. Der Snob" => [
        "Hans Mahnke",
        "Mila Kopp",
        "Heinz Baumann",
        "Rudolf Kalvius",
        "Immy Schell",
        "Klaramaria Skala",
        "Ortrud Bechler",
        "Ernst Barthels"
    ],
    "1964. Die Hose" => [
        "Paul Dahlke",
        "Cordula Trantow",
        "Eva-Ingeborg Scholz",
        "Georg Thomalla",
        "Joachim Teege",
        "Friedrich Maurer"
    ],
    "1965. Der Mord in der Rue Morgue" => [
        "Horst Tappert",
        "Erik Jelde",
        "Christian Marschall",
        "Christian Wolf",
        "Wolf Euba",
        "Fritz Straßner",
        "Robert Naegele",
        "Inge Schwanneke",
        "Wolfgang Dörich",
        "Claudia Bethge",
        "Fred Kallmann",
        "Jochen Hauer",
        "Christian Margulies"
    ]
];
