<?php

return [
    "1962-66 Sherlock Holmes" => [
        "Alexander Kerst",
        "Heinz Leo Fischer",
        "Ricarda Benndorf",
        "Fritz Brünske",
        "Ingeborg Thomass",
        "Brigitte Dryander",
        "Hans Jager",
        "Edith Neumeister",
        "Stella Giese",
        "Peter Arthur Stiege",
        "Charles Wirths",
        "Jochen Tietz",
        "Volker Hiltmann",
        "Ingo Eckert",
        "Eva Köhrer",
        "Rüdiger Renn",
        "Walter Rott",
        "Heinz Schimmelpfennig",
        "Manfred Kothe",
        "Josef Flöth",
        "Hans Joachim Steindamm",
        "Annegreth Ronald",
        "Peter Pasetti",
        "Klaus Behrendt",
        "Hans Zesch-Ballot",
        "Horst Tappert",
        "Norbert Kappen",
        "Adolf Ziegler",
        "Bum Krüger",
        "Gustl Datz",
        "Josef Manoth",
    ],
    "1966. Das blaue Zimmer" => [
        "Hans-Helmut Dickow",
        "Gisela Hoeter",
        "Dagmar Altrichter",
        "Gert Westphal",
        "Heinz Schimmelpfennig",
        "Ernst-Peter Horn",
        "Verena Buss",
        "Martin Ricelt",
        "Helmut Wöstmann",
        "Alfred Schlageter",
    ],
    "1966. Der Blutstropfen" => [
        "Herbert Bötticher",
        "Marlies Schönau",
        "Norbert Naegele",
        "Georg Kostya",
        "Christian Marschall",
        "Alexander Malachovsky",
        "Walter Ladengast",
        "Wolfgang Dörich",
        "Fritz Wilm Wallenborn",
        "Christof Nel",
        "Percy Adlon",
        "Edgar M. Böhlke",
        "Edmund Steinberger",
        "Claudia Bethge",
        "Sigrid Pawles",
        "Agnes Sorèl",
        "Marlies Compère",
    ],
    "1966. Nin Non Nan" => [
        "Ludwig Thiesen",
        "Norbert Kappen",
        "Ingrid Lammerding",
        "Günter Kemper",
        "Rüdiger Kirchstein",
        "Harald Meister",
        "Peter Oehme",
        "Wolf Schlamminger",
    ],
    "1966. Zwielicht" => [
        "Friedrich Maurer",
        "Lina Carstens",
    ],
    "1967. Glühendes Interesse" => [
        "Siegfried Lowitz",
        "Ursula Langrock",
        "Heinz Schimmelpfennig",
        "Roma Bahn",
        "Erna Grossmann",
        "Herbert Stass",
        "Walter Bluhm",
        "Horst-Werner Loos",
    ],
    "1968. Der unerwünschte Gast" => [
        "Hansjörg Felmy",
        "Herbert Weißbach",
        "Rolf Schult",
        "Friedrich Bauschulte",
        "Gerda Maurus",
    ],
    "1968. Die Falle" => [
        "Cläre Rapmund",
        "Richard Süssenguth",
        "Dietrich Frauboes",
        "Wolfgang Amerbacher",
        "Otto Czarski",
        "Norbert Langer",
        "Ulrich Herrlitz",
        "Peter Herzog",
        "Tobias Pagel",
        "Heinz Rabe",
        "Ute Martin",
        "Gisela Fritsch",
        "Rüdiger Lichti",
        "Joachim Pukaß",
        "Georg Tryphon",
        "Sigrid Lagemann",
        "Georg Braun",
        "Günter Hanke",
        "Konrad Wagner",
        "Steffen Müller",
        "Pierre Peters-Arnolds",
        "Stefan Schodrock",
        "Matthias Einert",
        "Alexander Bogdanoff",
        "Helmut Ahner",
    ],
    "1968. Fingerabdrücke lügen nicht" => [
        "Edith Heerdegen",
        "Herbert Bötticher",
        "Georg Kostya",
        "Hans Zesch-Ballot",
        "Marlies Schönau",
        "Uli Steigberg",
        "Christian Marschall",
        "Karin Christian",
        "Ulrich Frank",
        "Alexander Malachovsky",
    ],
    "1968. In Vertretung" => [
        "Heiner Schmidt",
        "Norbert Kappen",
        "Helmut Peine",
        "Otto Rouvel",
        "Richard Münch",
        "Kurt Postel",
    ],
    "1968. Niemandsmörder" => [
        "Michael Degen",
        "Günter König",
        "Gisela Fritsch",
        "Marianne Mosa",
        "Jürgen Hilken",
        "Heinz Stoewer",
        "Sonja Karzau",
        "Hans-Joachim Scherbening",
        "Werner Rosemann",
        "Karlheinz Schilling",
        "Wolfgang Engels",
        "Werner Kreindl",
        "Melanie de Graaf",
        "Peter Schmitz",
        "Gerhard Retschy",
    ],
    "1969. Bösendorfer" => [
        "Helmut Qualtinger",
        "Inge Birkmann",
        "Rosemarie von Schach",
    ],
    "1969. Die Schwestern Jouet" => [
        "Grete Mosheim",
        "Elisabeth Flickenschildt",
        "Blandine Ebinger",
    ],
    "1969. Häuser" => [
        "Karin Buchali",
        "Sigrun Höhler",
        "Maria Krasna",
        "Elisabeth Opitz",
        "Gisela Sauer",
        "Herbert Fleischmann",
        "Wolfgang Forester",
        "Kurt Lieck",
        "Alwin Joachim Meyer",
        "Wolfgang Peau",
        "Matthias Ponnier",
        "Heinz Schacht",
    ],
    "1970. Deutschland aufsagen~ Deutschland nachsagen" => [
        "Gabor Altorjay",
        "Louis Jean Bouchard",
        "Dorothee Brodowsky",
        "Ernst Brücher",
        "Nikolaus Brücher",
        "Christoph Caskel",
        "Margarita Sabartés de Delás",
        "Bojidar Dimov",
        "Dorothee Harten",
        "Paul Harten",
        "Friedrich Wilhelm Heubach",
        "Cestmir Janosek",
        "Katrin König",
        "Walther König",
        "Sigrid Langeheineken",
        "Helmut Leppien",
        "Petra Leppien",
        "János Mátyás",
        "Gerhard Rautenbach",
        "Herbert Schuldt",
    ],
    "1970. Freibrief für Mord" => [
        "Hans Quest",
        "Hans Cossy",
        "Robert Klupp",
        "Jürgen Goslar",
        "Monika Faber",
        "Jürgen Jung",
        "Alexander Malachovsky",
        "Monika Schwarz",
        "Christian Wolff",
        "Wolf Ackva",
        "Rüdiger Bahr",
        "Lina Carstens",
    ],
    "1970. Mord im Pfarrhaus" => [
        "Hans Quest",
        "Ingrid Capelle",
        "Elmar Wepper",
        "Edith Hancke",
        "Wolfgang Weiser",
        "Carin Braun",
        "Erika von Thellmann",
        "Paula Denk",
        "Hanne Wieder",
        "Jürgen Goslar",
        "Alf Tamin",
        "Günther Sauer",
        "Alexander Malachovsky",
    ],
    "1970. Mord nach Fahrplan" => [
        "Hans Caninenberg",
        "Helga Roloff",
        "Hans Cossy",
        "Heinz Stöwer",
        "Christian Marschall",
    ],
    "1971. Der Mäusesheriff" => [
        "Fritz Strassner",
        "Rüdiger Bahr",
        "Bernd-Holger Bonsels",
        "Paul Lasner",
        "Michael Gahr",
        "Frank Daniel",
        "Klaus W. Krause",
        "Kurt E. Ludwig",
        "Paul Rensal",
        "Ingeborg Schöner",
        "Anke Syring",
        "Gisela Traut",
    ],
    "1971. Die Frauen der Pariser Kommune" => [
        "Maria Barring",
        "Gretl Brand",
        "Ricarda Benndorf",
        "Verena Buss",
        "Carmen Renate Köper",
        "Marlene Riphahn",
        "Gisela Trowe",
        "Grete Wurm",
        "Rudolf Jürgen Bartsch",
    'Adolf "Addi" Furler',
    "Alois Garg",
        "Peter Lieck",
        "Matthias Ponnier",
        "Günther Sauer",
        "Robert Seibert",
        "Danielle Truchot",
    ],
    "1971. Jugend und Vollendung des Königs Henri Quatre" => [
        "Gerry Wolff",
        "Peter Reusse",
        "Inge Keller",
        "Eckhart Strehle",
        "Ruth Glöss",
        "Hans Teuscher",
    ],
    "1971. Leben und Tod der Marilyn Monroe" => [
        "Barbara Morawiecz",
        "Hans Mahnke",
        "Wiebke Paritz",
        "Karin Schlemmer",
        "Jutta Villinger",
        "Ludwig Anschütz",
        "Hans Peter Bögel",
        "Traugott Buhre",
        "Kurt Haars",
        "Wolfgang Höper",
        "Peter Roggisch",
        "Werner Schwuchow",
    ],
    "1972. Bilanz" => [
        "Hans Stadtmüller",
        "Therese Giehse",
    ],
    "1972. Calimero 1" => [
        "Wolfgang Ziffer",
        "Edith Hancke",
        "Renate Danz",
        "Horst Gentzen",
        "Franz-Otto Krüger",
        "Christa Häussler",
        "Wolfgang Völz",
        "Horst Schön",
        "Eberhard Storeck",
        "Inge Wolffberg",
        "Bettina Schön",
        "Gerd Duwner",
    ],
    "1972. Mann im Eis" => [
        "Wolfgang Büttner",
        "Karin Hübner",
        "Lina Carstens",
        "Hans Caninenberg",
        "Dieter Kirchlechner",
        "Leo Bardischewski",
        "Wega Jahnke-Wirth",
        "Monika Schwarz",
        "Imo Heite",
        "Christian Marschall",
    ],
    "1972. Mutter Courage und ihre Kinder" => [
        "Lya Dulitzkaya",
        "Elisabeth Danihelka",
        "Wolfgang Gasser",
        "Kurt Sobotka",
    ],
    "1973. Aasgeier" => [
        "Martin Held",
        "Lothar Blumhagen",
        "Petra von der Linde",
        "Herbert Weißbach",
        "Martin Hirthe",
        "Georg Tryphon",
        "Edith Hancke",
        "Stefan Wigger",
        "Dietrich Dorsch",
        "Michaela Pfeiffer",
        "Richard Süssenguth",
    ],
    "1973. Besuch in einer sterbenden Stadt" => [
        "Joachim Kerzel",
        "Christian Brückner",
        "Friedhelm Ptok",
        "Henning Gissel",
        "Rolf Schult",
    ],
    "1973. Demolition" => [
        "Hans-Peter Hallwachs",
        "Gert Günther Hoffmann",
        "Arnold Marquis",
        "Susanne Tremper",
        "Ingrid van Bergen",
        "Dieter Ranspach",
        "Uta Hallant",
        "Eduard Wandrey",
        "Anneliese Römer",
        "Tanja Berg",
        "Nero Brandenburg",
        "Josef Pelz von Felinau",
        "Andreas Mannkopff",
        "Helga Krauss",
        "Hubertus Bengsch",
        "Helma von Kieseritzky",
        "Rudi Schmitt",
        "Norbert Gescher",
        "Hermann Ebeling",
        "Hans Kwiet",
        "Erna Haffner",
        "Reinhard Kolldehoff",
        "Otto Czarski",
        "Klaus Jepsen",
        "Rosi Müller",
        "Friedrich W. Bauschulte",
        "Fritz Mellinger",
        "Georg Corten",
        "Joachim Kerzel",
        "Evamaria Miner",
        "Heinz Petruo",
        "Joachim Nottke",
        "Erika Matejka",
        "Walter Tappe",
        "Eric Vaessen",
        "Michaela Pfeiffer",
        "Paul Paulschmidt",
        "Burghard Klausner",
        "Gerd Holtenau",
        "Jürgen Wegner",
        "Mei Li Pfennig",
        "Hülya Laumer",
        "Hermann Wagner",
        "Rolf Marnitz",
        "Gertie Honeck",
        "Robert Matejka",
    ],
    "1973. John Jacob Astors letzte Fahrt" => [
        "Henning Venske",
        "Rolf Schult",
        "Carl Raddatz",
        "Jürgen Graf",
        "Josef Pelz von Felinau",
        "Lieselotte Rau",
        "Lothar Blumhagen",
        "Klaus Miedel",
        "Dieter Ranspach",
        "Friedhelm Ptok",
        "Hermann Ebeling",
        "Eric Vaessen",
        "Bernhard Minetti",
        "Paul Paulschmidt",
        "Rolf Marnitz",
        "Claus Hofer",
        "Henning Schlüter",
        "Klaus Herm",
        "Wolfgang Condrus",
        "Kai Blömer",
        "Erik von Loewis",
        "Thomas Pau",
    ],
    "1973. Macht der Finsternis" => [
        "Felix von Manteuffel",
        "Hans Quest",
        "Jürgen Jung",
        "Lina Carstens",
        "Hans Helmut Dickow",
        "Maria Singer",
        "Wega Jahnke-Wirth",
        "Georg Kostya",
        "Michael Lenz",
        "Anja Buczkowski",
        "Edmund Steinberger",
        "Marlies Compère",
        "Manfred Waltenberg",
        "Siglinde Heise-Röhrl",
        "Rudolf Neumann",
        "Christian Marschall",
    ],
    "1973. Merkwürdiges Beispiel einer weiblichen Rache" => [
        "Marion van de Kamp",
        "Horst Drinda",
        "Ingeborg Medschinski",
        "Ursula Staack",
        "Siegfried Wittlich",
        "Margit Bendokat",
        "Herwart Grosse",
    ],
    "1973. URB kann gar nichts" => [
        "Friedrich W. Bauschulte",
        "Marianne Mosa",
        "Arnold Marquis",
        "Kurt Lieck",
        "Ruth Pera",
        "Wolfgang Peau",
        "Christian Korp",
        "Eva Garg",
        "Ilse Strambowski",
        "Sabine Postel",
        "Alwin Joachim Meyer",
        "Oswald Fuchs",
        "Josef Meinertzhagen",
        "Rosemarie Vörkel",
        "Susanne Daus",
        "Ute Mansel",
    ],
    "1973. Widerworte aus der Küche" => [
        "Gisela Stein",
        "Friedhelm Ptok",
        "Sibylle Gilles",
        "Hermann Ebeling",
        "Kristin Zein",
        "Rolf Schult",
        "Evamaria Miner",
        "Friedrich W. Bauschulte",
        "Eva Manhardt",
        "Claus Hofer",
        "Caspar Engelbrecht",
    ],
    "1974. Das Spiegelbild" => [
        "Jürgen Jung",
        "Rüdiger Bahr",
        "Udo Wachtveitl",
        "Günther Beth",
        "Claudia Bethke",
        "Marlies Schönau",
        "Wolf Ackva",
        "Gert Anthoff",
        "Alexander Malachovsky",
        "Rolf Illig",
        "Ruth Küllenberg",
        "Marlies Compère",
        "Fred Büttner",
        "Wolfgang Dörich",
        "Wolf Petersen",
        "Georg Kostya",
        "Michael Lenz",
        "Christian Marschall",
    ],
    "1974. Der Tod trug einen Bart" => [
        "Lina Carstens",
        "Hans Quest",
        "Hans Helmut Dickow",
        "Joachim Wichmann",
        "Karl Renar",
        "Fred Büttner",
        "Rudolf Neumann",
        "Christian Marschall",
    ],
    "1974. Informationsfluß AG" => [
        "Erik Schumann",
        "Walter Jokisch",
        "Christian Marschall",
        "Fred Maire",
        "Klaus Kindler",
        "Alexander Hegarth",
        "Lis Kertelge",
        "Rüdiger Bahr",
        "Horst Sachtleben",
        "Mogens von Gadow",
        "Wolf Petersen",
        "Hartmut Neugebauer",
        "Paul Lasner",
    ],
    "1974. Mehr oder weniger kurz vor dem Tode" => [
        "Gisela Trowe",
        "Josef Meinertzhagen",
    'Adolf "Addi" Furler',
    "Katinka Hoffmann",
        "Marlene Riphahn",
        "Karl-Heinz Fiege",
        "Ingrid Steeger",
        "Wolf Martienzen",
        "Balduin Baas",
        "Irmgard Först",
        "Hansjörg Felmy",
        "Ruth Pera",
        "Edward Rothe",
        "Ilse Strambowski",
        "Klaus-Dieter Pittrich",
        "Eva Garg",
    ],
    "1974. Tod eines Physikers" => [
        "Felix von Manteuffel",
        "Johanna Mertinz",
        "Holger Hagen",
        "Leo Bardischewski",
        "Toni Berger",
        "Barbara Witow",
        "Rosemarie Fendel",
        "Peter Heusch",
        "Marlies Compère",
        "Geneta Fischer",
        "Gusti Kreissl",
        "Maria Stadler",
        "Franziska Walser",
        "Mechthild Zschau",
        "Alois Maria Giani",
        "Michael Habeck",
        "Winfried Küppers",
        "Ulf-Jürgen Wagner",
        "Reinhold Wichmann",
    ],
    "1974. Wickie" => [
        "Florian Halm",
        "Walter Reichelt",
        "Inge Schulz",
        "Alexandra Ludwig",
        "Horst Abraham",
        "Manfred Lichtenfeld",
        "Gernot Duda",
        "Kurt Zips",
        "Werner Abrolat",
        "Leo Bardischewski",
        "Eberhard Storeck",
        "Kurt E. Ludwig",
    ],
    "1976. Der Fall der Kommissare" => [
        "Erik Ode",
        "Reinhard Glemnitz",
        "Helma Seitz",
        "Horst Tappert",
        "Fritz Wepper",
        "Günther Neutze",
        "Karl Lieffen",
        "Klaus Schwarzkopf",
        "Edgar Ott",
        "Martin Hirthe",
        "Hansjörg Felmy",
        "Karin Eickelbaum",
        "Walter Richter",
        "Gustl Bayrhammer",
        "Friedrich W. Bauschulte",
        "Volker Brandt",
        "Jürgen Thormann",
        "Rainer Brandt",
        "Margot Leonhard",
        "Gert Günther Hoffmann",
        "Ursula Herwig",
    ],
    "1976. Momo" => [
        "Harald Leipnitz",
        "Irina Wanka",
        "Walter Bluhm",
        "Manfred Schott",
        "Hans Quest",
        "Wolfgang Kieling",
        "Franz Rudnick",
        "Walter Sedlmeyer",
        "Günter Strack",
        "Ilse Neubauer",
        "Gabriela Dossi",
        "Joachim Wichmann",
        "Margarete Graef",
        "Flortian Halm",
        "Nicole Sachtleben",
        "Martin Halm",
        "Dietrich Thoms",
        "Eva Pflug",
    ],
    "1977. Die Bakunin-Kassette" => [
        "Hans Magnus Enzensberger",
        "Hallgard Bruckhaus",
        "Christian Brückner",
        "Sibylle Gilles",
        "Renate Küster",
        "Erik von Loewis",
        "Rolf Schult",
        "Peter Fitz",
        "Erwin Schastok",
        "Helmut Krauss",
        "Peter Arnold",
    ],
    "1977. Die Eine-Million-Pfundnote" => [
        "Manfred Schott",
        "Siegfried Nürnberger",
        "Hans Timerding",
        "Monika Weniger",
        "Manfred Georg Herrmann",
        "Siegfried Meisner",
        "Wolfgang Breitenstein",
        "Gert Keller",
        "Ludwig Thiesen",
        "Willi Schneider",
    ],
    "1977. Ein Autobus~ so groß wie die Welt" => [
        "Harald Leipnitz",
        "Monika Peitsch",
        "Gert Günther Hoffmann",
        "Florian Halm",
        "Scarlet Lubowski",
        "Markus Klimmek",
        "Manuel Döpke",
        "Horst Abraham",
        "Lore Eberhard",
        "Angela Hillebrecht",
        "Helmut Stange",
        "Alexander Malachovsky",
    ],
    "1977. Kimba" => [
        "Oliver Grimm",
        "Marianne Lutz",
        "Harry Wüstenhagen",
        "Georg Corten",
        "Bettina Schön",
        "Wolfgang Draeger",
        "Klaus Miedel",
        "Maud Ackermann",
        "Klaus Miedel",
        "Andrea Pawlowski",
        "Cornelia Meinhardt",
        "Waltraut Habicht",
        "Renate Danz",
        "Friedrich Georg Beckhaus",
        "Rolf Schult",
    ],
    "1977. Meine Mutter darf es nie erfahren" => [
        "Harald Leipnitz",
        "Florian Halm",
        "Caroline van Bergen",
        "Fritz Tillmann",
        "Hartmut Becker",
        "Helmut Stange",
        "Horst Sachtleben",
        "Michael Habeck",
        "Ilse Neubauer",
        "Karin Kemke",
        "Manuel Döpke",
        "Michael Hoffmann",
        "Alexander Malachovsky",
    ],
    "1977. Weinen streng verboten" => [
        "Harald Leipnitz",
        "Florian Halm",
        "Caroline van Bergen",
        "Carolin Ohrner",
        "Julia Fischer",
        "Benno Hoffmann",
        "Fritz Tillmann",
        "Gert Günther Hoffmann",
        "Walter Schmidinger",
        "Wera Frydtberg",
        "Karina Urbach",
        "Kitty de Bryn",
        "Michael Habeck",
    ],
    "1978. Die Ameise~ die mit einer Fahne winkte" => [
        "Hans Joachim Bliese",
        "William Mockridge",
        "Heidemarie Rohweder",
        "Traugott Buhre",
        "Susanne Barth",
        "Ulrich Lauterbach",
    ],
    "1978. Die Tote im Götakanal" => [
        "Rita Russek",
        "Matthias Ponnier",
        "Charles Wirths",
        "Heta Mantscheff",
        "Hubert Suschka",
        "Herbert Stass",
        "Ernst Jacobi",
        "Horst Beilke",
        "Christian Brückner",
        "Verena Buss",
        "Else Brückner-Rüggeberg",
        "Friedrich von Bülow",
        "Dieter Eppler",
        "Peter Franzon",
        "Gert Keller",
        "Bernd Lau",
        "Marianne Lochert",
        "Joachim Nottke",
        "Karin Schröder",
        "Michael Thomas",
    ],
    "1978. Tödlicher Sand" => [
        "Holger Hagen",
        "Hans Musäus",
        "Irmgard Först",
        "Susanne Beck",
        "Lambert Hamel",
        "Otto Kurth",
        "Paul Hoffmann",
        "Andrea Wildner",
    ],
    "1980. Chala" => [
        "Günter Dockerill",
    ],
    "1980. Der alte Mann und die Medaille" => [
        "Hans-Helmut Dickow",
    ],
    "1980. Der Hobbit" => [
        "Martin Benrath",
        "Horst Bollmann",
        "Bernhard Minetti",
        "Heinz Schacht",
        "Wolfgang Spier",
        "Friedrich W. Bauschulte",
        "Herbert Weißbach",
        "Herbert Grünbaum",
        "Rolf Schult",
        "Heinz Theo Branding",
        "Martin Hirthe",
        "Uta Hallant",
        "Lieselotte Rau",
        "Heinz Theo Branding",
        "Jürgen von Manger",
        "Benno Kusche",
    ],
    "1980. Der Märtyrer" => [
        "Werner Rundshagen",
    ],
    "1980. Der Pfeil Gottes" => [
        "Hans Paetsch",
    ],
    "1980. Die Herrschaft der Spinne" => [
        "Hans Paetsch",
    ],
    "1980. Gebt dem Kaiser~ was des Kaisers ist" => [
        "Günter Dockerill",
    ],
    "1980. Perpétue und die Gewöhnung ans Unglück" => [
        "Günter Dockerill",
    ],
    "1981. Das Alphatrio" => [
        "Günter Mack",
        "Joachim Nottke",
        "Elfriede Irral",
        "Klaus-Peter Grap",
        "Ernst-August Schepmann",
        "Rainer Basedow",
    ],
    "1981. Die schwarze Witwe von Loudon" => [
        "Eva Vaitl",
        "Robert Atzorn",
        "Peter Musäus",
        "Wolfgang Büttner",
        "Hans Quest",
        "Harry Kalenberg",
        "Christian Marschall",
        "Grete Wurm",
        "Claudia Bethge",
        "Dieter Brammer",
        "Peter Kapell",
        "Helmut Stange",
        "Karin Kernke",
        "Ado Riegler",
        "Claudia Golling",
        "Thomas Reiner",
        "Karl Sibold",
        "Gustl Datz",
        "Leo Bardischewski",
        "Emily Reuer",
        "Renate Grosser",
    ],
    "1981. Die Unendliche Geschichte" => [
        "Harald Leipnitz",
        "Clemens Kleiber",
        "Matthias von Stegmann",
        "Horst Breitenfeld",
        "Helga Dners",
        "Gert Günther Hoffmann",
        "Hanne Wieder",
        "Franz Rudnick",
        "Karl Renar",
        "Günter Sauer",
        "Michael Lenz",
        "Christop Quest",
        "Harry Kalenberg",
        "Kurt Zips",
        "Alexander Malachovsky",
        "Ulli Philipp",
        "Jürgen Goslar",
        "Wolfgang Büttner",
        "Horst Sachtleben",
        "Emely Reuer",
        "Herbert Bötticher",
        "Renate Grosser",
        "Ursula Traun",
        "Jochen Striebeck",
        "Harry Kalenberg",
        "Michael Lenz",
    ],
    "1981. Ein tragischer Unfall" => [
        "Michael Lenz",
        "Ilse Neubauer",
        "Herbert Fleischmann",
        "Christian Marschall",
        "Helga Anders",
        "Gustl Datz",
        "Mario Andersen",
        "Günther Sauer",
        "Lilian Westphal",
        "Gerd Silberbauer",
        "Joachim Höppner",
        "Gerhard Acktum",
        "Ulf Wagner",
        "Mathias Eysen",
    ],
    "1981. Hatch will heiraten" => [
        "Friedrich W. Bauschulte",
        "Klaus Herm",
        "Karin Grüger",
        "Rudi Schmitt",
        "Heinz Rabe",
        "Krikor Melikyan",
        "Eric Vaessen",
        "Manuel Vaessen",
    ],
    "1981. Im Zeichen des Kain" => [
        "Michael Gahr",
        "Claudia Bethge",
        "Hansjörg Felmy",
        "Gert Günther Hoffmann",
        "Otto Stern",
        "Arthur Brauss",
        "Bernd Stephan",
        "Joachim Wichmann",
        "Michael Lenz",
        "Kornelia Boje",
        "Doris Schade",
        "Christine Hammacher",
        "Wolf Ackva",
        "Helmut Stange",
    ],
    "1981. Monolog für Kontrabaß" => [
        "Walter Schmidinger",
    ],
    "1981. Robinsons Insel" => [
        "Friedrich W. Bauschulte",
        "Klaus Herm",
        "Lothar Blumhagen",
        "Beate Hasenau",
        "Hermann Ebeling",
        "Otto Czarski",
        "Heinz Spitzner",
        "Norbert Gescher",
    ],
    "1982. Heut liegt was in der Luft" => [
        "Jürgen Thormann",
        "Horst Bollmann",
        "Helmut Wildt",
        "Barbara Adolf",
        "Walter Pfeil",
        "Klaus Nägelen",
        "Heinz Rabe",
        "Maria Krasna",
        "Friedrich W. Bauschulte",
        "Klaus-Peter Grap",
        "Gerd Duwner",
        "Klaus Miedel",
        "Friedhelm Ortmann",
        "Ingrid Neuhaus",
        "Heinz-Theo Branding",
        "Christian Rode",
        "Almut Eggert",
        "Peter Schlesinger",
        "Gilla Gotthardt",
    ],
    "1982. Schmetterling mit Hakenkreuzen" => [
        "Aljoscha Sebald",
        "Katharina Lopinsky",
        "Rüdiger Bahr",
        "Horst Sachtleben",
        "Harald Leipnitz",
        "Gert Günther Hoffmann",
        "Siemen Rühaak",
        "Hans-Günter Martens",
        "Gerd Eichen",
        "Gerhard Becker",
        "Eric P. Caspar",
        "Axel Wostry",
        "Jürgen Jung",
        "Christiane Merthan",
        "Wolf Goldan",
        "Gerhard Mohr",
        "Bernd Herberger",
        "Kurt Goldstein",
        "Christoph Lindert",
        "Hans Peder Hermansen",
        "Michael Hoffmann",
        "Ute Mora",
    ],
    "1983. Blau und Schwarz" => [
        "Gert Günther Hoffmann",
        "Manfred Seipold",
        "Karin Anselm",
        "Peter Fricke",
    ],
    "1983. Outsider in Amsterdam" => [
        "Hans-Peter Hallwachs",
        "Wolfgang Büttner",
        "Charles Wirths",
        "Matthias Ponnier",
        "Heinrich Giskes",
        "Martin Semmelrogge",
        "Gerd Andresen",
        "Nina Danzeisen",
        "Dieter Eppler",
        "Alf Marholm",
        "Heinz Meier",
    ],
    "1983. Wohnrecht auf Lebenszeit" => [
        "Peter Lieck",
        "Wolf Aniol",
        "Renate Fuhrmann",
        "Ricarda Benndorf",
        "Hans Keller",
    ],
    "1984. Auf zwei Planeten" => [
        "Angela Büttner",
        "Joachim Wichmann",
        "Franz Rudnick",
        "Ralph Schicha",
        "Martin Umbach",
        "Christine Mederer",
        "Harry Kalenberg",
        "Rolf Illig",
        "Eva Astor",
        "Herbert Weicker",
        "Peter Bertram",
        "Hans Quest",
        "Christian Marschall",
        "Ulrich Frank"
    ]
    ];
